# Site settings
sitename: "Building Violations"
domain: "buildingviolation.com"
year: 2015
email: info@buildingviolation.com
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
